# Generated by Django 4.2.5 on 2023-11-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0002_remove_testimonio_fecha_testimonio_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='testimonio',
            field=models.CharField(max_length=2000),
        ),
    ]
